### ISSUE TITLE
Progress bar disappears when terminal is resized

### ISSUE THREAD

**Issue by Linux123123** [pollev/bash_progress_bar#4]
After trying out the script for a bit I noticed that when your try to **resize** the terminal when progress bar is running it **disappears** / **moves up** from the bottom.

OS: Ubuntu 20.04 
Terminal: `gnome-terminal`
Shell: `bash`

**Comment by pollev** [comment]
Hi man,

~~This is a consequence of setting up the scroll area for a specifc amount of terminal lines.~~
~~There is an easy workaround for this but it could have a non-negligable performance impact.~~

~~Instead of just calling `draw_progress_bar`. You could also call `setup_scroll_area` every time rather than just at the start of the script.~~

~~To do this properly, I would need to figure out somehow at each update if the terminal size has changed and update the scroll area accordingly. I will have a look at this but I'm not certain this will be a straightforward fix.~~

~~In the meanwhile I recommend using the workaround.~~

**Comment by pollev** [comment]
Update: Actually this was a really easy fix: see commit 4dae8a07bda9311f3b1f718bca0b5fa42ae2d76c
It should be good now. Please try and let me know if there are still issues
